# Generated by Django 5.1.2 on 2024-10-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_lesson_created_at_lesson_updated_at_lessoncomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessoncomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
