# Generated by Django 5.1.2 on 2024-10-31 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_alter_lesson_cash_alter_lesson_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessontag',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
