# Generated by Django 5.0.3 on 2024-11-10 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_rename_is_paid_lesson_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='payment',
            new_name='is_paid',
        ),
    ]
